#!/usr/bin/env bash
# apply-layout.sh (*FR:Brunel*)
#
# Creates the polyphony-dev tmux layout (8 panes).
#
# Layout:
#   | palestrina | finn     | bentham   |
#   |            |---------------------|
#   |            | byrd     | josquin   |
#   |            |---------------------|
#   |            | tallis   | comenius  |
#   |            |---------------------|
#   |            | victoria            |
#
# Split tree:
#   Window (%0) — initial pane is palestrina
#   ├── split -h -p 70 → left (palestrina), right (R)
#   └── right column split into 4 rows:
#       ├── row 1: finn (top 25% of R), then split right → bentham
#       ├── row 2: byrd, then split right → josquin
#       ├── row 3: tallis, then split right → comenius
#       └── row 4: victoria (full width, bottom)
#
# Usage: apply-layout.sh [tmux-session]
#   Default session: polyphony
#
# Output: writes /tmp/polyphony-panes.env with PANE_* vars for spawn_member.sh.

set -e

TMUX_SESSION="${1:-polyphony}"
WORK_DIR="/home/ai-teams/workspace"
PANE_ENV="/tmp/polyphony-panes.env"

if ! tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
    echo "ERROR: tmux session '$TMUX_SESSION' not found." >&2
    exit 1
fi

# ── Pane 0: palestrina (left 30%, full height) ───────────────────────────────
PANE_PALESTRINA=$(tmux list-panes -t "$TMUX_SESSION" -F '#{pane_id}' | head -1)

# ── Split right column (right 70%) ───────────────────────────────────────────
PANE_RIGHT=$(tmux split-window -t "$PANE_PALESTRINA" -d -h -p 70 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split right column into 4 rows ───────────────────────────────────────────
# Row 1 top (25% of right)
PANE_FINN="$PANE_RIGHT"
PANE_R2=$(tmux split-window -t "$PANE_RIGHT" -d -v -p 75 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# Row 2 (33% of remaining)
PANE_BYRD="$PANE_R2"
PANE_R3=$(tmux split-window -t "$PANE_R2" -d -v -p 67 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# Row 3 (50% of remaining)
PANE_TALLIS="$PANE_R3"
PANE_VICTORIA=$(tmux split-window -t "$PANE_R3" -d -v -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split rows 1-3 horizontally 50/50 ────────────────────────────────────────
PANE_BENTHAM=$(tmux split-window  -t "$PANE_FINN"   -d -h -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')
PANE_JOSQUIN=$(tmux split-window  -t "$PANE_BYRD"   -d -h -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')
PANE_COMENIUS=$(tmux split-window -t "$PANE_TALLIS"  -d -h -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Label panes ───────────────────────────────────────────────────────────────
tmux select-pane -t "$PANE_PALESTRINA" -T "palestrina"
tmux select-pane -t "$PANE_FINN"       -T "finn"
tmux select-pane -t "$PANE_BENTHAM"    -T "bentham"
tmux select-pane -t "$PANE_BYRD"       -T "byrd"
tmux select-pane -t "$PANE_JOSQUIN"    -T "josquin"
tmux select-pane -t "$PANE_TALLIS"     -T "tallis"
tmux select-pane -t "$PANE_COMENIUS"   -T "comenius"
tmux select-pane -t "$PANE_VICTORIA"   -T "victoria"

tmux set-option -t "$TMUX_SESSION" pane-border-format " #{pane_title} "
tmux set-option -t "$TMUX_SESSION" pane-border-status top

tmux select-pane -t "$PANE_PALESTRINA"

# ── Write pane env file ───────────────────────────────────────────────────────
cat > "$PANE_ENV" << EOF
# polyphony-dev tmux pane IDs — source before spawn_member.sh
# Generated by apply-layout.sh at $(date)
export PANE_PALESTRINA=${PANE_PALESTRINA}
export PANE_FINN=${PANE_FINN}
export PANE_BENTHAM=${PANE_BENTHAM}
export PANE_BYRD=${PANE_BYRD}
export PANE_JOSQUIN=${PANE_JOSQUIN}
export PANE_TALLIS=${PANE_TALLIS}
export PANE_COMENIUS=${PANE_COMENIUS}
export PANE_VICTORIA=${PANE_VICTORIA}
EOF

echo "Layout applied to session: $TMUX_SESSION"
echo "Pane IDs written to: $PANE_ENV"
echo ""
echo "  palestrina: $PANE_PALESTRINA"
echo "  finn:       $PANE_FINN"
echo "  bentham:    $PANE_BENTHAM"
echo "  byrd:       $PANE_BYRD"
echo "  josquin:    $PANE_JOSQUIN"
echo "  tallis:     $PANE_TALLIS"
echo "  comenius:   $PANE_COMENIUS"
echo "  victoria:   $PANE_VICTORIA"
