#!/usr/bin/env bash
# apply-layout.sh (*FR:Brunel*)
#
# Creates the polyphony-dev tmux layout (8 panes).
#
# Layout:
#   | palestrina | byrd     | josquin   |
#   |            |---------------------|
#   | finn       | tallis   | bentham   |
#   |            |---------------------|
#   |            | comenius | victoria  |
#
# Split tree:
#   Window (%0) — initial pane is palestrina
#   ├── split -h -p 70 → left (L), right (R)
#   ├── split L -v -p 50 → palestrina (top), finn (bottom)
#   └── split R into 3 rows, each split -h -p 50:
#       ├── row 1: byrd | josquin
#       ├── row 2: tallis | bentham
#       └── row 3: comenius | victoria
#
# Usage: apply-layout.sh [tmux-session]
#   Default session: polyphony
#
# Output: writes /tmp/polyphony-panes.env with PANE_* vars for spawn_member.sh.

set -e

TMUX_SESSION="${1:-polyphony}"
WORK_DIR="/home/ai-teams/workspace"
PANE_ENV="/tmp/polyphony-panes.env"

if ! tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
    echo "ERROR: tmux session '$TMUX_SESSION' not found." >&2
    exit 1
fi

# ── Pane 0: palestrina (initial pane, will be left-top) ──────────────────────
PANE_PALESTRINA=$(tmux list-panes -t "$TMUX_SESSION" -F '#{pane_id}' | head -1)

# ── Split right column (right 70%) ───────────────────────────────────────────
PANE_RIGHT=$(tmux split-window -t "$PANE_PALESTRINA" -d -h -p 70 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split left column: finn below palestrina ──────────────────────────────────
PANE_FINN=$(tmux split-window -t "$PANE_PALESTRINA" -d -v -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split right column into 3 equal rows ─────────────────────────────────────
PANE_BYRD="$PANE_RIGHT"
PANE_R2=$(tmux split-window -t "$PANE_RIGHT" -d -v -p 67 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

PANE_TALLIS="$PANE_R2"
PANE_COMENIUS=$(tmux split-window -t "$PANE_R2" -d -v -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split each right row horizontally 50/50 ──────────────────────────────────
PANE_JOSQUIN=$(tmux split-window  -t "$PANE_BYRD"    -d -h -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')
PANE_BENTHAM=$(tmux split-window  -t "$PANE_TALLIS"  -d -h -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')
PANE_VICTORIA=$(tmux split-window -t "$PANE_COMENIUS" -d -h -p 50 -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Label panes ───────────────────────────────────────────────────────────────
tmux select-pane -t "$PANE_PALESTRINA" -T "palestrina"
tmux select-pane -t "$PANE_FINN"       -T "finn"
tmux select-pane -t "$PANE_BYRD"       -T "byrd"
tmux select-pane -t "$PANE_JOSQUIN"    -T "josquin"
tmux select-pane -t "$PANE_TALLIS"     -T "tallis"
tmux select-pane -t "$PANE_BENTHAM"    -T "bentham"
tmux select-pane -t "$PANE_COMENIUS"   -T "comenius"
tmux select-pane -t "$PANE_VICTORIA"   -T "victoria"

tmux set-option -t "$TMUX_SESSION" pane-border-format " #{pane_title} "
tmux set-option -t "$TMUX_SESSION" pane-border-status top

tmux select-pane -t "$PANE_PALESTRINA"

# ── Write pane env file ───────────────────────────────────────────────────────
cat > "$PANE_ENV" << EOF
# polyphony-dev tmux pane IDs — source before spawn_member.sh
# Generated by apply-layout.sh at $(date)
export PANE_PALESTRINA=${PANE_PALESTRINA}
export PANE_FINN=${PANE_FINN}
export PANE_BYRD=${PANE_BYRD}
export PANE_JOSQUIN=${PANE_JOSQUIN}
export PANE_TALLIS=${PANE_TALLIS}
export PANE_BENTHAM=${PANE_BENTHAM}
export PANE_COMENIUS=${PANE_COMENIUS}
export PANE_VICTORIA=${PANE_VICTORIA}
EOF

echo "Layout applied to session: $TMUX_SESSION"
echo "Pane IDs written to: $PANE_ENV"
echo ""
echo "  palestrina: $PANE_PALESTRINA"
echo "  finn:       $PANE_FINN"
echo "  byrd:       $PANE_BYRD"
echo "  josquin:    $PANE_JOSQUIN"
echo "  tallis:     $PANE_TALLIS"
echo "  bentham:    $PANE_BENTHAM"
echo "  comenius:   $PANE_COMENIUS"
echo "  victoria:   $PANE_VICTORIA"
