#!/usr/bin/env bash
# apply-layout.sh (*FR:Brunel*)
#
# Creates the polyphony-dev tmux layout (8 panes).
# Uses absolute sizes (-l) not percentages (-p) — works when split from SSH context.
#
# Layout:
#   | palestrina | byrd     | josquin   |
#   |            |---------------------|
#   | finn       | tallis   | bentham   |
#   |            |---------------------|
#   |            | comenius | victoria  |
#
# Usage: apply-layout.sh [tmux-session]
#   Default session: POLY

set -e

TMUX_SESSION="${1:-POLY}"
WORK_DIR="$HOME/workspace"
PANE_ENV="/tmp/polyphony-panes.env"

if ! tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
    echo "ERROR: tmux session '$TMUX_SESSION' not found." >&2
    exit 1
fi

# ── Read current pane dimensions ─────────────────────────────────────────────
PANE_PALESTRINA=$(tmux list-panes -t "$TMUX_SESSION" -F '#{pane_id}' | head -1)
W=$(tmux display-message -t "$TMUX_SESSION" -p '#{window_width}')
H=$(tmux display-message -t "$TMUX_SESSION" -p '#{window_height}')

LEFT_W=$(( W * 30 / 100 ))
RIGHT_W=$(( W - LEFT_W - 1 ))
ROW_H=$(( H / 3 ))
HALF_RIGHT=$(( RIGHT_W / 2 ))

# ── Split right column (70%) ──────────────────────────────────────────────────
PANE_RIGHT=$(tmux split-window -t "$PANE_PALESTRINA" -d -h -l "$RIGHT_W" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split left column: finn below palestrina ──────────────────────────────────
PANE_FINN=$(tmux split-window -t "$PANE_PALESTRINA" -d -v -l "$(( H / 2 ))" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split right into 3 rows ───────────────────────────────────────────────────
PANE_BYRD="$PANE_RIGHT"
PANE_R2=$(tmux split-window -t "$PANE_RIGHT" -d -v -l "$(( ROW_H * 2 ))" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')
PANE_TALLIS="$PANE_R2"
PANE_COMENIUS=$(tmux split-window -t "$PANE_R2" -d -v -l "$ROW_H" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Split each row 50/50 ──────────────────────────────────────────────────────
PANE_JOSQUIN=$(tmux split-window  -t "$PANE_BYRD"     -d -h -l "$HALF_RIGHT" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')
PANE_BENTHAM=$(tmux split-window  -t "$PANE_TALLIS"   -d -h -l "$HALF_RIGHT" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')
PANE_VICTORIA=$(tmux split-window -t "$PANE_COMENIUS" -d -h -l "$HALF_RIGHT" -c "$WORK_DIR" -P -F '#{pane_id}' 'bash --norc -i')

# ── Label panes ───────────────────────────────────────────────────────────────
tmux select-pane -t "$PANE_PALESTRINA" -T "palestrina"
tmux select-pane -t "$PANE_FINN"       -T "finn"
tmux select-pane -t "$PANE_BYRD"       -T "byrd"
tmux select-pane -t "$PANE_JOSQUIN"    -T "josquin"
tmux select-pane -t "$PANE_TALLIS"     -T "tallis"
tmux select-pane -t "$PANE_BENTHAM"    -T "bentham"
tmux select-pane -t "$PANE_COMENIUS"   -T "comenius"
tmux select-pane -t "$PANE_VICTORIA"   -T "victoria"

tmux set-option -t "$TMUX_SESSION" pane-border-format " #{pane_title} "
tmux set-option -t "$TMUX_SESSION" pane-border-status top
tmux select-pane -t "$PANE_PALESTRINA"

cat > "$PANE_ENV" << EOF
# polyphony-dev tmux pane IDs — source before spawn_member.sh
# Generated by apply-layout.sh at $(date)
export PANE_PALESTRINA=${PANE_PALESTRINA}
export PANE_FINN=${PANE_FINN}
export PANE_BYRD=${PANE_BYRD}
export PANE_JOSQUIN=${PANE_JOSQUIN}
export PANE_TALLIS=${PANE_TALLIS}
export PANE_BENTHAM=${PANE_BENTHAM}
export PANE_COMENIUS=${PANE_COMENIUS}
export PANE_VICTORIA=${PANE_VICTORIA}
EOF

echo "Layout applied: ${W}x${H} → left=${LEFT_W} right=${RIGHT_W} row_h=${ROW_H}"
